CREATE TABLE [dbo].[Books]
(
	[Id] INT IDENTITY (1, 1) PRIMARY KEY, 
    [Name] NVARCHAR(250) NOT NULL, 
    [Description] NVARCHAR(MAX) NOT NULL, 
    [InArchive] BIT NOT NULL DEFAULT 0, 
    [Genre] TINYINT NOT NULL, 
    [RegistrationDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE()
)
