CREATE TABLE [dbo].[Users]
(
	[Id] INT IDENTITY (1, 1) PRIMARY KEY, 
    [Name] NVARCHAR(100) NOT NULL, 
    [Email] NVARCHAR(100) NOT NULL, 
    [DateOfBirth] DATETIME2 NOT NULL,
    [RegistrationDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE()
)
